<?php

namespace AppBundle\Repository;

/**
 * PositionGPSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionGPSRepository extends \Doctrine\ORM\EntityRepository
{
}
